### ISSUE TITLE
Are you going to support EXR with DWAA?

### ISSUE THREAD

**Issue by FidoAnh** [LogicReinc/LogicReinc.BlendFarm#30] opened 2022-04-05 05:37 UTC
EXR with DWAA is smaller than PNG, they save a lot of space and don't loose much information like PNG! I hope one day, you make my wish come true.

**Comment by LogicReinc** [comment] 2022-04-05 18:13
Sadly replacing the file format isn't as simple as just allowing you to select it. The underlying system is required to merge images together, and if the drawing system doesn't support the format, it would need to be converted to a bitmap first. Which in term will remove any benefits EXR offers. Size of images shouldn't be a bottleneck compared to other communication unless you're rendering 8-16k images, and even then it might be neglectable compared to other processes.

For animation rendering there might be a possibility to do it as no merging takes place, but for splitted rendering it has very low priority as it means adding new dependencies to the project and rewriting some parts.

Currently there are far more important features that I plan on prioritizing (namely, animation rendering performance improvements, which I like to do this month).
If animation is what you care about add a comment, and I might consider it part of the release after this month.

This is partially a duplicate of #13 .
So preferably you continue the discussion there as it covers a broader topic.

**Closed by LogicReinc** 2022-04-05 18:13 UTC
Labels: Duplicate
