### ISSUE TITLE
Does not render: Render fail: Missing files?

### ISSUE THREAD

**Issue by toamz** [LogicReinc/LogicReinc.BlendFarm#4] opened 2021-05-09 21:13 UTC
I have downloaded demo file from Blender.org [Lone Monk](https://download.blender.org/demo/cycles/lone-monk_cycles_and_exposure-node_demo.blend) and tried to render it with BlendFarm.
After deep research of how this program works  ;) , I found that the Python script crashes on line 25: `scn = bpy.data.scenes["Scene"]`

The problem is, that the script assumes that there exists a scene called "Scene", but this file was using name "daylight".
I'd suggest using `scn = bpy.context.scene` (current scene) instead of `scn = bpy.data.scenes["Scene"]`

PS. Thank you for creating such an awsome network renderer 👍 
Btw. is there a better way of debugging the python script than adding a lot of print-s?

**Comment by LogicReinc** [comment] 2021-05-09 21:21
Hey toamz,
I happen to have had someone else with this issue yea, and it was planned to be fixed in the next release.
But thanks for informing me anyway!

The python script is intended to be simple, and do minimal work (to prevent it from breaking future releases etc). 
And I don't believe the software allows you to alter it. (Software should check if render.py is the same as it is in memory)
There is no easy way to use the render.py outside of BlendFarm as it was intended to only be used by BlendFarm (it generates config files that are read by Blender).
At the moment, render.py also does some special stuff regarding render order to fix an issue with Blender not rendering tiles correctly, Blendfarm knows how to handle this in response.

I plan on adding a new feature, and fix this bug likely early this week, if you need to render something now I suggest just renaming the scene as its just 2 seconds work.

Good luck

**Comment by Lynchon83** [comment] 2021-05-11 15:35
Same problem here, great to see its already solved.

**Comment by LogicReinc** [comment] 2021-05-12 18:15
Fixed in version v1.0.5

**Closed by LogicReinc** 2021-05-12 18:15 UTC
Labels: Solved In Next Release
